version: '3.8'

services:
  nextjs:
    image: node:18
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - '3000:3000'
    command: sh -c "npm install && npm run dev"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: